---
abstract: 'Interact with remote applications that use SAJAX.'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.03
  Test::More: 0.41
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SAJAX
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  English: 0
  JE: 0.033
  LWP::UserAgent: 5.819
  List::MoreUtils: 0
  Moose: 0.77
  MooseX::StrictConstructor: 0.08
  MooseX::Types::URI: 0.02
  URI: 1.22
  URI::QueryParam: 0
  namespace::clean: 0.04
  perl: 5.8.3
resources:
  homepage: http://github.com/dougwilson/perl5-net-sajax/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-net-sajax.git
version: 0.001
