---
abstract: 'Interact with remote applications that use SAJAX.'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.03
  Test::MockObject: 0
  Test::More: 0.41
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SAJAX
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  English: 0
  perl: 5.8.3
resources:
  homepage: http://github.com/dougwilson/perl5-net-sajax/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-net-sajax.git
version: 0.102
