---
abstract: 'Interact with remote applications that use SAJAX.'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  Test::Exception: 0.03
  Test::MockObject: 0
  Test::More: 0.41
  Test::Requires: 0.02
  URI::Escape: 0
configure_requires:
  Module::Build: 0.31
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SAJAX
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Net::SAJAX:
    file: lib/Net/SAJAX.pm
    version: 0.106
  Net::SAJAX::Exception:
    file: lib/Net/SAJAX/Exception.pm
    version: 0.106
  Net::SAJAX::Exception::JavaScriptConversion:
    file: lib/Net/SAJAX/Exception/JavaScriptConversion.pm
    version: 0.106
  Net::SAJAX::Exception::JavaScriptEvaluation:
    file: lib/Net/SAJAX/Exception/JavaScriptEvaluation.pm
    version: 0.106
  Net::SAJAX::Exception::MethodArguments:
    file: lib/Net/SAJAX/Exception/MethodArguments.pm
    version: 0.106
  Net::SAJAX::Exception::RemoteError:
    file: lib/Net/SAJAX/Exception/RemoteError.pm
    version: 0.106
  Net::SAJAX::Exception::Response:
    file: lib/Net/SAJAX/Exception/Response.pm
    version: 0.106
requires:
  Carp: 0
  English: 0
  HTTP::Request::Common: 5.814
  JE: 0.033
  LWP::UserAgent: 5.819
  List::MoreUtils: 0
  Moose: 0.77
  MooseX::StrictConstructor: 0.08
  MooseX::Types::URI: 0.02
  URI: 1.22
  URI::QueryParam: 0
  namespace::clean: 0.04
  perl: 5.008003
resources:
  homepage: http://github.com/dougwilson/perl5-net-sajax/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-net-sajax.git
version: 0.106
